Update of French strings.txt, short_description.txt & full_description.txt in French
4nubhav/WhatsDeleted pull request #23
Opened 2021-03-16 10:37 UTC by Sitavi

Update of French strings.txt to correct some details, and translation of short_description.txt & full_description.txt in French.

2021-09-07 21:44 UTC, Zakaria16 requested changes

2021-09-07 21:44 UTC, Zakaria16 commented on app/src/main/res/values-fr/strings.xml
>      <string name="allow_storage_permission_msg">Les messages et les médias ne peuvent pas être enregistrés sans accès au stockage. Redémarrez l'application et autorisez la permission.</string>
Concerning **l'application** the apostrophe should be escaped or it will give build error

solution: **l\\'application**

2021-09-10 14:36 UTC, Sitavi commented
@Zakaria16 Thanks, done!

2021-11-22 17:59 UTC, merged

2021-11-22 18:00 UTC, 4nubhav commented
Thanks!